version: '3.9'

x-app: &default-app
  image: "${DOCKER_REGISTRY}/charpoints/${PLATFORM}/app:dev"
  volumes:
    - ./app:/srv
  build:
    context: ./app
  platform: $PLATFORM
  environment:
    - DATABASE_URL=postgres://app:app@db/app
    - NODE_ENV=development  
    - DETECTION_API  
    - STORYBOOK_PORT
    - YARN_REGISTRY

services:
  app:
    <<: *default-app
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    depends_on:
      - migrate

  srv:
    <<: *default-app
    command: wait-for-it db:5432 -- yarn srv start:dev
    depends_on:
      - migrate
    ports:
      - "${SERVER_PORT}:80"

  storybook:
    <<: *default-app
    command: yarn web storybook
    ports:
      - "${STORYBOOK_PORT}:${STORYBOOK_PORT}"

  migrate:
    <<: *default-app
    command: wait-for-it db:5432 -- yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
