version: '3.1'

services:
  app:
    image: "charpoints-app"
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./app:/srv
    command: yarn sr start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate

  srv:
    image: "charpoints-app"
    volumes:
      - ./app:/srv
    command: yarn srv start:dev
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate
    ports:
      - "${SERVER_PORT}:80"

  web:
    image: "charpoints-app"
    volumes:
      - ./app:/srv
    command: yarn web start:dev
    environment:
      - WEBPACK_PORT
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    depends_on:
      - srv

  storybook:
    image: "charpoints-app"
    volumes:
      - ./app:/srv
    command: yarn web storybook
    environment:
      - STORYBOOK_PORT
    ports:
      - "${STORYBOOK_PORT}:${STORYBOOK_PORT}"

  migrate:
    image: "charpoints-app"
    volumes:
      - ./app:/srv
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    command: yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
