version: '3.9'

volumes:
  db-data:

x-app: &default-app
  image: "charpoints-app"
  environment:
    - DATABASE_URL=postgres://app:app@db/app
    - DETECTION_API  
  restart: on-failure


services:
  srv:
    <<: *default-app
    command: wait-for-it db:5432 -- yarn srv start
    ports:
      - "${SERVER_PORT}:80"
    depends_on:
      - migrate

  migrate:
    <<: *default-app
    command: wait-for-it db:5432 -- yarn db-migrate up
    depends_on:
      - db
  db:
    image: "postgres:13"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
