version: '3.4'

services:
  server:
    image: "charpoints-app"
    command: yarn srv start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    restart: on-failure
    ports:
      - "${SERVER_PORT}:80"
    depends_on:
      - migration

  migration:
    image: "charpoints-app"
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    command: yarn db-migrate up
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app

