version: 2.1
jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker:
        version: 19.03.13
      - checkout
        # start proprietary DB using private Docker image
        # with credentials stored in the UI
      - run: |
        docker-compose config
