version: 2.1
jobs:
  build:
    machine: true
    environment:
      - STORYBOOK_PORT: 9090
      - SERVER_PORT: 8080
      - WEBPACK_PORT: 8081
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.28.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run: docker-compose build
      - run: | 
          docker-compose run --rm app yarn install
          docker-compose run --rm app yarn build
      - run: | 
          docker-compose run --rm app yarn srv test
      - run: | 
          docker-compose run --rm app yarn core test
