version: 2.1
jobs:
  build:
    machine: true
    environment:
      - STORYBOOK_PORT: 9090
      - WEB_PORT: 8080
    steps:
      - checkout
      - run: docker-compose build
      - run: | 
          docker-compose run --rm app yarn install
          docker-compose run --rm app yarn build
          export SERVER_PORT=8080
      - run: | 
          docker-compose run --rm app yarn srv test
      - run: | 
          docker-compose run --rm app yarn core test
